#define YOU_BOT_LEFT_FORWARD_WHEEL_MOTOR_SIM_NAME   "rollingJoint_fl"
#define YOU_BOT_RIGHT_FORWARD_WHEEL_MOTOR_SIM_NAME  "rollingJoint_fr"
#define YOU_BOT_LEFT_BACKWARD_WHEEL_MOTOR_SIM_NAME  "rollingJoint_rl"
#define YOU_BOT_RIGHT_BACKWARD_WHEEL_MOTOR_SIM_NAME "rollingJoint_rr" 

#define YOU_BOT_WHEEL_BASE_WIDTH (double)316.0
#define YOU_BOT_WHEEL_BASE_LENTH (double)456.0
#define YOU_BOT_WHEEL_DEAMETER (double)68.0