#define YOU_BOT_LEFT_FORWARD_WHEEL_MOTOR_SIM_NAME   "rollingJoint_fl"
#define YOU_BOT_RIGHT_FORWARD_WHEEL_MOTOR_SIM_NAME  "rollingJoint_fr"
#define YOU_BOT_LEFT_BACKWARD_WHEEL_MOTOR_SIM_NAME  "rollingJoint_rl"
#define YOU_BOT_RIGHT_BACKWARD_WHEEL_MOTOR_SIM_NAME "rollingJoint_rr" 

#define YOU_BOT_WHEEL_BASE_WIDTH (double) 0.316
#define YOU_BOT_WHEEL_BASE_LENTH (double) 0.471
#define YOU_BOT_WHEEL_DEAMETER (double) 0.475

#define YOU_BOT_PLATFORM_X_MAX_VELOCITY 0.03
#define YOU_BOT_PLATFORM_X_MIN_VELOCITY 0.002

#define YOU_BOT_PLATFORM_Y_MAX_VELOCITY 0.005
#define YOU_BOT_PLATFORM_Y_MIN_VELOCITY 0.0

#define YOU_BOT_PLATFORM_Z_MAX_VELOCITY  0.008
#define YOU_BOT_PLATFORM_Z_MIN_VELOCITY -0.008