#define YOU_BOT_LEFT_FORWARD_WHEEL_MOTOR_SIM_NAME   ""
#define YOU_BOT_RIGHT_FORWARD_WHEEL_MOTOR_SIM_NAME  ""
#define YOU_BOT_LEFT_BACKWARD_WHEEL_MOTOR_SIM_NAME  ""
#define YOU_BOT_RIGHT_BACKWARD_WHEEL_MOTOR_SIM_NAME "" 

#define YOU_BOT_WHEEL_BASE_WIDTH 0.0
#define YOU_BOT_WHEEL_BASE_LENTH 0.0